languange: generic 
sudo: required
services:
  - docker 

before_install:
  - docker build -t rodrigorras/docker-react -f Dockerfile.dev . 

script:
  #- docker run rodrigorras/docker-react npm run test -- --coverage 
  - docker run -e CI=true rodrigorras/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-743771023549"
  bucket_path: "docker-react"
  on: 
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
 